// Emits the bundled sample PDFs as base64 for the single-file build, which has
// no separate files to fetch.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, '..', 'public', 'samples');
const OUT = path.join(HERE, '..', 'src', 'ui', 'samples.inline.js');

const wanted = [
  'authentic_INV-101538.pdf',
  'authentic_INV-101551.pdf',
  'fraudulent_INV-101544.pdf',
  'tampered_INV-101541.pdf',
];

const entries = wanted.map((name) => {
  const b64 = fs.readFileSync(path.join(SRC, name)).toString('base64');
  return `  ${JSON.stringify(name)}: '${b64}',`;
});

fs.writeFileSync(OUT, `// Generated by scripts/inline-samples.mjs - do not edit.
export const INLINE_SAMPLES = {
${entries.join('\n')}
};

export function decodeSample(name) {
  const b64 = INLINE_SAMPLES[name];
  if (!b64) throw new Error(\`No bundled sample named \${name}\`);
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
`);
console.log(`wrote ${OUT} (${wanted.length} samples, ${(fs.statSync(OUT).size / 1024).toFixed(0)} kB)`);
